# Generated by Django 5.2 on 2025-05-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_active',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
